# Generated by Django 5.2.3 on 2025-06-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='65e3c6aa11c954c150686bce72d6ffa016013617', max_length=40, unique=True),
        ),
    ]
