# Generated by Django 5.2.3 on 2025-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='revoked',
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
