apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  namespace: django-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc  # Use EFS for shared storage across pods